/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ugmsystem;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ugmsystem.Login.currentUser;



/**
 *This is an interface class that displays sections of commodities being advertised by different vendors
 * @author fayaldosa
 */
public class Sections extends javax.swing.JFrame {

 static Sections color = new Sections();

    /**
     *
     */
    public static Boolean check;

    /**
     *
     */
    public static Boolean check2;

    /**
     *
     */
    public static Boolean check3;

    /**
     *
     */
    public static Boolean radio1;

    /**
     *
     */
    public static Boolean radio2;

    /**
     *
     */
    public static Boolean radio3;

    /**
     *
     */
    public static Boolean radio4;

    /**
     *
     */
    public static Boolean SelectSection;

    /**
     *
     */
    public static Boolean T=true;
    /**
     * Creates new form Books
     */
    public Sections() {
        initComponents();
        setTitle("Book Section");
        setLocationRelativeTo(null);

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();

        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("Advertisement 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(363, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/logo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(222, 89, 0));
        jLabel3.setText("Sections");

        Back.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/orangeBack2.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jButton11.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        jButton11.setText("View");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        jButton12.setText("Buy");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel9.setText("Select Section");

        jComboBox1.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Books", "Clothes", "Furniture" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel11.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton4);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/myAccount2.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/smallHome.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Picture1logout.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Picture1mesv1.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton1)
                                .addGap(27, 27, 27)
                                .addComponent(jRadioButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jRadioButton4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(285, 285, 285)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed

     Search.color.getContentPane().setBackground(Color.WHITE);
        Search.color.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BackActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     CommodityBuyer c = null;
       String itemText=null;
         itemText = (String) jComboBox1.getSelectedItem();
  

  check=itemText.equals("Books");
  check2=itemText.equals("Clothes");
  check3=itemText.equals("Furniture");
        radio1 = jRadioButton1.isSelected();
  radio2=jRadioButton2.isSelected();
   radio3=jRadioButton3.isSelected();
    radio4=jRadioButton4.isSelected();
  
  
           if (itemText.equals("Books")) {

      if (jRadioButton1.isSelected()){
              
          if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
      
                
            }
      
      else if (jRadioButton2.isSelected()){
         if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
      
            }
         
      else if (jRadioButton3.isSelected()){
              if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
       
                
            }
      else   if (jRadioButton4.isSelected()){
              
          if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
         
                
            }

           }

           
         else  if (itemText.equals("Clothes")) {

      if (jRadioButton1.isSelected()){
              
             if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
        
                
            }
      
      else  if (jRadioButton2.isSelected()){
              
               if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
    
            }
         
          else if (jRadioButton3.isSelected()){
              
              if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
              
            }
           else  if (jRadioButton4.isSelected()){
              
            if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
            
            }

           }

             else if (itemText.equals("Furniture")) {

      if (jRadioButton1.isSelected()){
              
            if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
        
            }
      
        else if (jRadioButton2.isSelected()){
              
                if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
        
            }
         
        else   if (jRadioButton3.isSelected()){
              
             if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
       
            }
          else   if (jRadioButton4.isSelected()){
              
              if (c== null){
              c=new CommodityBuyer();
          }
          c.setVisible(true);
          this.setVisible(false);
         
                
            }

           }




    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed


    String itemText= null;
           itemText = (String) jComboBox1.getSelectedItem();

        if (itemText.equals("Books")) {
              jLabel4.setText("");
              jLabel5.setText("");
            jLabel6.setText("");
            jLabel11.setText("");
            jLabel10.setText("");
            
        
            if(!Commodity.getBooksSectionAds().get(2).isEmpty() ) {
                jLabel4.setText(Commodity.getBooksSectionAds().get(2));
            }
           if(!Commodity.getBooksSectionAds().get(9).isEmpty() && !Commodity.getBooksSectionAds().get(9).equals(Commodity.getBooksSectionAds().get(2)) ) {
               jLabel5.setText(Commodity.getBooksSectionAds().get(9));
           }
            if(!Commodity.getBooksSectionAds().get(16).isEmpty() &&   !Commodity.getBooksSectionAds().get(16).equals(Commodity.getBooksSectionAds().get(2))
                     && !Commodity.getBooksSectionAds().get(16).equals(Commodity.getBooksSectionAds().get(9))){
                
                jLabel6.setText(Commodity.getBooksSectionAds().get(16));
            }
          
        
           if(!Commodity.getBooksSectionAds().get(23).isEmpty() && ! Commodity.getBooksSectionAds().get(23).equals(Commodity.getBooksSectionAds().get(2))
                    && !Commodity.getBooksSectionAds().get(23).equals(Commodity.getBooksSectionAds().get(9)) 
                    && !Commodity.getBooksSectionAds().get(23).equals(Commodity.getBooksSectionAds().get(16))){ 
                jLabel11.setText(Commodity.getBooksSectionAds().get(23));
                
           }

            try {

                BufferedImage s = ImageIO.read(Sections.class.getResource("../Pictures/book2.png"));
                BufferedImage s2 = ImageIO.read(Sections.class.getResource("../Pictures/book1.png"));
                BufferedImage s3 = ImageIO.read(Sections.class.getResource("../Pictures/book3.png"));
                Icon icon = new ImageIcon(s);
                Icon icon2 = new ImageIcon(s2);
                Icon icon3 = new ImageIcon(s3);
                jLabel1.setIcon(icon);
                jLabel7.setIcon(icon2);
                jLabel8.setIcon(icon3);
                
                  if(!Commodity.getBooksSectionAds().get(25).isEmpty()  && ! Commodity.getBooksSectionAds().get(25).equals(Commodity.getBooksSectionAds().get(4))
                              && ! Commodity.getBooksSectionAds().get(25).equals(Commodity.getBooksSectionAds().get(11)) 
                              && ! Commodity.getBooksSectionAds().get(25).equals(Commodity.getBooksSectionAds().get(18)))
                     {  
                      ImageIcon icon4 = new ImageIcon (Commodity.getBooksSectionAds().get(25));
                 jLabel10.setIcon(icon4);
                
            }
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         
        }
        
        
        
            if (itemText.equals("Clothes")) {
                  jLabel4.setText("");
              jLabel5.setText("");
            jLabel6.setText("");
            jLabel11.setText("");
            jLabel10.setText("");
                
               
            if(!Commodity.getClothesSectionAds().get(2).isEmpty() ) {
                jLabel4.setText(Commodity.getClothesSectionAds().get(2));
            }
           if(!Commodity.getClothesSectionAds().get(9).isEmpty() && !Commodity.getClothesSectionAds().get(9).equals(Commodity.getClothesSectionAds().get(2)) ) {
               jLabel5.setText(Commodity.getClothesSectionAds().get(9));
           }
            if(!Commodity.getClothesSectionAds().get(16).isEmpty() &&   !Commodity.getClothesSectionAds().get(16).equals(Commodity.getClothesSectionAds().get(2))
                     && !Commodity.getClothesSectionAds().get(16).equals(Commodity.getClothesSectionAds().get(9))){
                
                jLabel6.setText(Commodity.getClothesSectionAds().get(16));
            }
          
        
           if(!Commodity.getClothesSectionAds().get(23).isEmpty() && ! Commodity.getClothesSectionAds().get(23).equals(Commodity.getClothesSectionAds().get(2))
                    && !Commodity.getClothesSectionAds().get(23).equals(Commodity.getClothesSectionAds().get(9)) 
                    && !Commodity.getClothesSectionAds().get(23).equals(Commodity.getClothesSectionAds().get(16))){ 
                jLabel11.setText(Commodity.getClothesSectionAds().get(23));
                
           }

            try {

                BufferedImage s = ImageIO.read(Sections.class.getResource("../Pictures/d-1.png"));
                BufferedImage s2 = ImageIO.read(Sections.class.getResource("../Pictures/shoes.png"));
                BufferedImage s3 = ImageIO.read(Sections.class.getResource("../Pictures/m.png"));
                Icon icon = new ImageIcon(s);
                Icon icon2 = new ImageIcon(s2);
                Icon icon3 = new ImageIcon(s3);
                jLabel1.setIcon(icon);
                jLabel7.setIcon(icon2);
                jLabel8.setIcon(icon3);
                
                      if(!Commodity.getClothesSectionAds().get(25).isEmpty()  && ! Commodity.getClothesSectionAds().get(25).equals(Commodity.getClothesSectionAds().get(4))
                              && ! Commodity.getClothesSectionAds().get(25).equals(Commodity.getClothesSectionAds().get(11)) 
                              && ! Commodity.getClothesSectionAds().get(25).equals(Commodity.getClothesSectionAds().get(18))){
                      ImageIcon icon4 = new ImageIcon (Commodity.getClothesSectionAds().get(25));
                 jLabel10.setIcon(icon4);
                
            }
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
               if (itemText.equals("Furniture")) {
                   
                   jLabel4.setText("");
                   jLabel5.setText("");
                   jLabel6.setText("");
                   jLabel11.setText("");
                   jLabel10.setText("");
                   
        if(!Commodity.getFurnSectionAds().get(2).isEmpty() ) {
                jLabel4.setText(Commodity.getFurnSectionAds().get(2));
            }
           if(!Commodity.getFurnSectionAds().get(9).isEmpty() && !Commodity.getFurnSectionAds().get(9).equals(Commodity.getFurnSectionAds().get(2)) ) {
               jLabel5.setText(Commodity.getFurnSectionAds().get(9));
           }
            if(!Commodity.getFurnSectionAds().get(16).isEmpty() &&   !Commodity.getFurnSectionAds().get(16).equals(Commodity.getFurnSectionAds().get(2))
                     && !Commodity.getFurnSectionAds().get(16).equals(Commodity.getFurnSectionAds().get(9))){
                
                jLabel6.setText(Commodity.getFurnSectionAds().get(16));
            }
          
        
           if(!Commodity.getFurnSectionAds().get(23).isEmpty() && ! Commodity.getFurnSectionAds().get(23).equals(Commodity.getFurnSectionAds().get(2))
                    && !Commodity.getFurnSectionAds().get(23).equals(Commodity.getFurnSectionAds().get(9)) 
                    && !Commodity.getFurnSectionAds().get(23).equals(Commodity.getFurnSectionAds().get(16))){ 
                jLabel11.setText(Commodity.getFurnSectionAds().get(23));
                
           }

            try {

                BufferedImage s = ImageIO.read(Sections.class.getResource("../Pictures/ch.png"));
                BufferedImage s2 = ImageIO.read(Sections.class.getResource("../Pictures/l.png"));
                BufferedImage s3 = ImageIO.read(Sections.class.getResource("../Pictures/s.png"));
                Icon icon = new ImageIcon(s);
                Icon icon2 = new ImageIcon(s2);
                Icon icon3 = new ImageIcon(s3);
                jLabel1.setIcon(icon);
                jLabel7.setIcon(icon2);
                jLabel8.setIcon(icon3);
                
                      if(!Commodity.getFurnSectionAds().get(25).isEmpty() && ! Commodity.getFurnSectionAds().get(25).equals(Commodity.getFurnSectionAds().get(4))
                              && ! Commodity.getFurnSectionAds().get(25).equals(Commodity.getFurnSectionAds().get(11)) 
                              && ! Commodity.getFurnSectionAds().get(25).equals(Commodity.getFurnSectionAds().get(18))){  
                      ImageIcon icon4 = new ImageIcon (Commodity.getFurnSectionAds().get(25));
                 jLabel10.setIcon(icon4);
                
            }
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 if(currentUser.isGuest()){
         JOptionPane.showMessageDialog(this, "You can't access this page, register first.");
        }
         
        
      else{
            try {
            Login.currentUser = Buyer.findUser(Login.vendor.getId());
        
        } catch (IOException ex) {
            Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
        }
 
       PaymentInfo c = null;
       String itemText=null;
         itemText = (String) jComboBox1.getSelectedItem();
  

  check=itemText.equals("Books");
  check2=itemText.equals("Clothes");
  check3=itemText.equals("Furniture");
        radio1 = jRadioButton1.isSelected();
  radio2=jRadioButton2.isSelected();
   radio3=jRadioButton3.isSelected();
    radio4=jRadioButton4.isSelected();
  
  
           if (itemText.equals("Books")) {

      if (jRadioButton1.isSelected()){
              
          if (c== null){
              c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
      
                
            }
      
      else if (jRadioButton2.isSelected()){
         if (c== null){
              c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
      
            }
         
      else if (jRadioButton3.isSelected()){
              if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
       
                
            }
      else   if (jRadioButton4.isSelected()){
              
          if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
         
                
            }

           }

           
         else  if (itemText.equals("Clothes")) {

      if (jRadioButton1.isSelected()){
              
             if (c== null){
              c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
        
                
            }
      
      else  if (jRadioButton2.isSelected()){
              
               if (c== null){
              c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
    
            }
         
          else if (jRadioButton3.isSelected()){
              
              if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
              
            }
           else  if (jRadioButton4.isSelected()){
              
            if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
            
            }

           }

             else if (itemText.equals("Furniture")) {

      if (jRadioButton1.isSelected()){
              
            if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
        
            }
      
        else if (jRadioButton2.isSelected()){
              
                if (c== null){
              c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
        
            }
         
        else   if (jRadioButton3.isSelected()){
              
             if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
       
            }
          else   if (jRadioButton4.isSelected()){
              
              if (c== null){
               c=new PaymentInfo();
          }
          c.setVisible(true);
          this.setVisible(false);
         
                
            }

           }
  
        
 }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed

        
          if(currentUser.isGuest()){
         JOptionPane.showMessageDialog(this, "You can't access this page, register first.");
        }
         
        
       else{
        
        try {
            Login.currentUser = Buyer.findUser(Login.vendor.getId());

            MyAccount.color.getContentPane().setBackground(Color.WHITE);
            MyAccount.color.setVisible(true);
            this.setVisible(false);

        } catch (IOException ex) {
            Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed

        
        Search.color.getContentPane().setBackground(Color.WHITE);
        Search.color.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed

        if(currentUser.isGuest()){
         JOptionPane.showMessageDialog(this, "You can't access this page, register first.");
        }
         
        
       else{
        try {
            Login.currentUser = Buyer.findUser(Login.vendor.getId());

           Login.currentUser=null;
        MainMenu.color.getContentPane().setBackground(Color.WHITE);
        MainMenu.color.setVisible(true);
        this.setVisible(false);

        } catch (IOException ex) {
            Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
       
         if(currentUser.isGuest()){
         JOptionPane.showMessageDialog(this, "You can't access this page, register first.");
        }
         
        
       else{
        try {
            Login.currentUser = Buyer.findUser(Login.vendor.getId());

           
        
        ChatPage.color.getContentPane().setBackground(Color.WHITE);
        ChatPage.color.setVisible(true);
        this.setVisible(false);

        } catch (IOException ex) {
            Logger.getLogger(Sections.class.getName()).log(Level.SEVERE, null, ex);
        }
        }  
        
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sections().setVisible(true);
                
                
              
              
                
                
                
  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
